- name: 'apt | repository'
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' state=present

- name: 'apt | install postgresql'
  apt: name=postgresql-9.4 state=latest

- name: 'apt | install postgresql-contrib'
  apt: name=postgresql-contrib-9.4 state=latest force=yes
  when: db_hstore is defined and db_hstore

- name: 'start service'
  action: service name=postgresql state=started
