---
  - name: docker_host | apt | install packages
    apt: name={{ item }} state=latest
    with_items:
      - apt-transport-https
      - docker-engine

  - name: docker_host | start service
    action: service name=docker state=started

  # - name: Ensure docker-compose is installed and available
  #   shell: curl -L https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose

  - name: docker_host | set attributes for docker-compose
    file:
      path="/usr/local/bin/docker-compose"
      state=file
      mode=0755
      owner={{ ansible_ssh_user }}
      group=docker

  - name: docker_host | Ensure that target directories exists with correct access rights
    file: path={{ item }} state=directory mode=0755 owner={{ apps_user }}
    become: true
    with_items:
      - '{{ docker_meta_path }}'
      - '{{ docker_data_path }}'
