---
# Basic server setup.
- hosts: all
  remote_user: root
  become: true
  roles:
    - { role: 'system_common' }

- hosts: all
  remote_user: root
  become: true
  roles:
    - { role: 'nginx', tags: ['nginx']  }
    - { role: 'nodejs' }
    - { role: 'redis', tags: ['redis'] }
    - { role: 'postgresql', tags: ['postgres'] }

# apps user environment.
- hosts: all
  remote_user: root
  become: true
  become_user: '{{ apps_user }}'
  roles:
    - { role: 'rbenv' }
    # - { role: 'eye', tags: ['eye'] }
