# Basic server setup.
---

- hosts: all
  remote_user: root
  roles:
    - system_common
    - nginx
    - docker_host

- hosts: legacy_hosting
  remote_user: dvps
  become: true
  roles:
    - { role: 'nodejs' }
    - { role: 'redis', tags: ['redis'] }
    - { role: 'postgresql', tags: ['postgres'] }

# apps user environment.
- hosts: legacy_hosting
  remote_user: root
  become: true
  become_user: '{{ apps_user }}'
  roles:
    - { role: 'rbenv' }
