# System update, requirements.
- name: apt | update cache
  apt: update_cache=yes

# TODO: uncomment if you need to enable system upgrading.
# - name: 'apt | upgrade dist'
#   apt: upgrade=dist

- name: apt | install packages
  apt: name={{item}} state=latest
  with_items: '{{ packages }}'

- name: set hostname
  hostname: name={{ (not server_hostname and inventory_hostname) or server_hostname }}

- name: ntp | enable sync
  service: name=ntp state=started enabled=yes

# Date and time
# - name: 'datetime | remove localtime file'
#   file: 'path=/etc/localtime state=absent'
# - name: 'datetime | link Moscow localtime file'
#   file: 'src=/usr/share/zoneinfo/Europe/Moscow dest=/etc/localtime state=link'

# locale settings
- name: locale | locale-gen
  shell: 'locale-gen {{ default_locale }}'

- name: locale | default environment
  lineinfile: "dest=/etc/default/locale state=present line='LC_ALL=\"{{ default_locale }}\"'"

- include: users.yml
- include: ssh.yml