# ssh settings
# - name: ssh | prevent root login
#   replace: "dest=/etc/ssh/sshd_config regexp='^#PermitRootLogin yes$' replace='PermitRootLogin no'"

- name: ssh | disable password authentication
  replace: "dest=/etc/ssh/sshd_config regexp='^PasswordAuthentication yes$' replace='PasswordAuthentication no'"
